
services:
  sterlingPdf:
    container_name: sterling-pdf
    image: frooodle/s-pdf:latest
    restart: unless-stopped
    ports:
      - 7080:8080
    environment:
      - DOCKER_ENABLE_SECURITY=false
    volumes:
      - ./data/trainingData:/usr/share/tesseract-ocr/4.00/tessdata
      - ./data/extraConfigs:/configs
