
services:
  DockerRegistryUi:
    container_name: docker-registry-ui
    image: quiq/docker-registry-ui
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./data/config.yml:/opt/config.yml
      - /data/data:/opt/data